### ISSUE TITLE
protelis-interpreter and kotlin-stdlib must not be forced into the classpath

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis-KDoc-generator#15]
The plugin should first check if such dependencies are available in the classpath before pushing them in, and anyway it must provide configuration to exclude their resolution.

**Comment by DanySK** [comment]
The bug still stands even after merging #16

**Comment by metaphori** [comment]
@DanySK may you show the error message here?

**Comment by DanySK** [comment]
Dependencies are pulled in anyway.
My feeling is that there is a design issue. Extensions settings are set **AFTER** the plugin application, but dependencies are computed **BEFORE**.

So even if you add
```
    Protelis2KotlinDoc {
        automaticDependencies.set(false)
    }
```
the value of `automaticDependencies` is read at plugin application, defaults to `true`, and then changed to `false`, but the damage is done. Note: I had the same issue with git-sensitive-semantic-versioning.

Defaulting to `false` would disable the injection feature no matter what.

The best thing here is probably to create a protelisDoc dependency configuration, fed that to the kotlin compilation, and manage it in the dependency configuration block. However, the fastest workaround is to just give up automatic dependency injection and document that we require protelis-interpreter and kotlin-stdlib.
The problem is, at that point, that we become bound to kotlin-stdlib even though the project does not require it.

Argh

**Comment by metaphori** [comment]
@DanySK How may we check if this is fixed now?

**Comment by DanySK** [comment]
this has been fixed now by the new dependency configuration:

```kotlin
dependencies {
    protelisdoc("your.group:your-dependency:version")
}
```
